### ISSUE TITLE
Menubar icon doesn't't switch color when changing dark mode or desktop picture Big Sur

### ISSUE THREAD

**Issue by etrahretep** [DeveloperMaris/ToolReleases#10]
Icon stays dark when auto dark mode. Also doesn't change color when changing desktop picture in Big Sur

**Comment by DeveloperMaris** [comment]
Thank you for your feedback!
I want to clarify - does the issue with icon not switching using auto dark mode happening on Catalina or Big Sur? 

Big Sur isn't supported yet, but will be in upcoming updates.

**Comment by DeveloperMaris** [comment]
Title of the issue already answered my question. 

I will undress these issues in future updates, when Big Sur will be supported.

Thank you!

**Comment by etrahretep** [comment]
It did work before the last update...

**Comment by DeveloperMaris** [comment]
It seams than macOS Big Sur for now displays status bar icons only in white color for light and dark mode.

ToolReleases now have a whote status bar icon by default, so it will be visible in both modes correctly in the latest version. 
Try it out!
