### ISSUE TITLE
Last Updated string off by a week

### ISSUE THREAD

**Issue by woolie** [DeveloperMaris/ToolReleases#11]
The Beta Release suggest that Xcode 12 b2 was released on July 7th, today is July 21st and it says last released: `1 Week ago`, which doesn't seem correct.

<img width="316" alt="Screen Shot 2020-07-21 at 11 27 00 AM" src="https://user-images.githubusercontent.com/62043/88092396-417b4100-cb45-11ea-85c9-7abf3dadb359.png">

**Comment by woolie** [comment]
(maybe at noon it will start to say `2 weeks ago`, but since the granularity is `a week` that distinction seems a little wrong.

**Comment by DeveloperMaris** [comment]
Thank you @woolie for reporting this issue, I will look into it.

**Comment by woolie** [comment]
Pacific. BTW: as a follow-on, afternoon shows `2 weeks ago` correctly.

**Comment by DeveloperMaris** [comment]
Thanks, it calculates the dates not from the beginning of the day, but from exact time when release was published.

In the next release I will update this to be more accurate.
