### ISSUE TITLE
Overlapping issues

### ISSUE THREAD

**Issue by Nils89** [DeveloperMaris/ToolReleases#39]
First, thank you for the great app.

I have an overlpapping issue if the scrollbar is visible:
![Bildschirmfoto 2021-03-05 um 22 11 18](https://user-images.githubusercontent.com/23194902/110174053-cd558b00-7dff-11eb-903d-f8f587da03e9.png)
The Time is cut off

Without a scrollbar it fits:
![Bildschirmfoto 2021-03-05 um 22 12 34](https://user-images.githubusercontent.com/23194902/110174100-e78f6900-7dff-11eb-9bd3-679d91395c43.png)

**Comment by DeveloperMaris** [comment]
Thank you for your feedback, I will address this issue in the next release cycle.
When it will be fixed, I will leave a message about that here.

**Comment by DeveloperMaris** [comment]
Fixed this issue in v1.4.1.
