### ISSUE TITLE
Issues with light mode and "Reduce Transparency" accessibility setting

### ISSUE THREAD

**Issue by woolie** [DeveloperMaris/ToolReleases#4]
In light more (Catalina 10.15.5 (19F101)), when using the "Reduce Transparency" accessibility mode, the icon looks to be disabled (because it is so light).

Also the menu highlighting is too subtle to be used. See included screen captures:
<img width="96" alt="Reduced Icon" src="https://user-images.githubusercontent.com/62043/86817139-78c3fb00-c039-11ea-844b-6bc1e6bb3b45.png">
<img width="121" alt="Non-Reduced Icon" src="https://user-images.githubusercontent.com/62043/86817146-7a8dbe80-c039-11ea-8402-be236b23b315.png">
<img width="203" alt="Reduced Menu" src="https://user-images.githubusercontent.com/62043/86817165-81b4cc80-c039-11ea-9e54-c46316f64099.png">

**Comment by DeveloperMaris** [comment]
Thank you, @woolie for your feedback. 
I will address this issue in the next release. :)

**Comment by DeveloperMaris** [comment]
@woolie Latest update includes fixes for the accessibility mode.
