### ISSUE TITLE
missing minimum system version is sparkle feed

### ISSUE THREAD

**Issue by core-code** [DeveloperMaris/ToolReleases#43]
the newest update is presented even to users who don't run 'Big Sur', although it won't run for them

adding 

`			<sparkle:minimumSystemVersion>11.0</sparkle:minimumSystemVersion>
`

to the newest item in your sparkle feed should help

**Comment by DeveloperMaris** [comment]
Thank you for reporting this, will fix it and release a patch as soon as possible.

**Comment by core-code** [comment]
thanks glad its useful

don't think a new release is required as the missing line can just be added to the feed here:

`https://developermaris.github.io/ToolReleases/appcast.xml`

**Comment by DeveloperMaris** [comment]
As a quick fix I added the necessary line to the RSS feed, but as it is a dynamic script which generates it, this line **for now** is added to all versions.
Will fix that when I will have more free time. 

Thank you @core-code! 🙂
For now I will leave this ticket still open.

**Comment by DeveloperMaris** [comment]
It seems that Sparkle 1.23.0 version has some kind of issues with the `sparkle:minimumSystemVersion`. 
If I set it to `<sparkle:minimumSystemVersion>11.0</sparkle:minimumSystemVersion>` then it does not let me update anymore.
So to be able to update (running Big Sur) decided to set minimum version to `<sparkle:minimumSystemVersion>10.16</sparkle:minimumSystemVersion>` which will let Big Sur users to update and Catalina users to stay on the previous version.

**Comment by core-code** [comment]
whether NSProcessInfo.processInfo.operatingSystemVersion yields 10.16 or 11.0 depends on whether Xcode < 12 was used to compile the code in question.

**Comment by core-code** [comment]
@DeveloperMaris can you report this problem upstream here? https://github.com/sparkle-project/Sparkle/issues thanks

**Comment by DeveloperMaris** [comment]
Version 1.3.7 (previous one) was compiled using the Xcode 11 and the new one using Xcode 12.
I remember when the Big Sur came out that its version initially was set as 10.16 not 11, but that was in the early macOS betas. Didn't though that previous Xcode release could still read this value incorrectly. 
But it kinda explains why when I was checking out the previous release code and compiling locally - everything was fine and it provided the update correctly, but the already released version didn't see the update.

Thanks for suggestion, will create an issue, but first let me try to get hands on Xcode 11 to verify this scenario.
