### ISSUE TITLE
Animation on launch makes the app feel slow

### ISSUE THREAD

**Issue by deandmx** [DeveloperMaris/ToolReleases#45]
My issue is the animation when you click the icon makes the app feel slow. Every other menubar item I have (apart from Notification Centre) appears instantly on click.

**Comment by DeveloperMaris** [comment]
Thank you for raising my attention to this.
I will look into this in the upcoming releases and see how I can improve this situation so that the animation would happen quicker and not feel slow or do not happen at all.

**Comment by DeveloperMaris** [comment]
With the version 1.5.0 the initial animation is removed.
