### ISSUE TITLE
Relative time from future

### ISSUE THREAD

**Issue by aprosvetova** [DeveloperMaris/ToolReleases#5]
<img width="297" alt="Screenshot 2020-07-07 at 21 13 25" src="https://user-images.githubusercontent.com/2043497/86824360-b86d0000-c096-11ea-80a9-783d7b4abb29.png">
It says "in 48 minutes" and I don't think it's right.
Could be related to timezone problems, I have UTC+3.

**Comment by rmaloney3** [comment]
The Apple RSS feed that this is based on is showing a future date, so it's not a timezone issue. I'm in the same timezone as the feed, and I see the same thing as you. Not sure if there's much that can be done about this one.

![image](https://user-images.githubusercontent.com/1734252/86825174-ea08ab80-c043-11ea-83b0-3f3a830a1e50.png)

**Comment by aprosvetova** [comment]
:(
Shame on you, Apple.

**Comment by DeveloperMaris** [comment]
Thanks for the feedback @aprosvetova, unfortunately, there is nothing we can do here - Apple controls the feed and I don't think that it would be correct to implement any additional logic or calculations on the received time. :) 

Let's hope that Apple will not put incorrect release times in the RSS feed in the future. :)
