### ISSUE TITLE
Add Filter (for Version)

### ISSUE THREAD

**Issue by danielkbx** [DeveloperMaris/ToolReleases#6]
I would be great to have a filter, so I can filter (e.g. for iOS 14 only) beta versions.

**Comment by DeveloperMaris** [comment]
Thanks for your feedback, this feature is already in development! :) 
Stay tuned! 😉

**Comment by DeveloperMaris** [comment]
@danielkbx I'm proud to announce that the latest update includes the new search option.
Check it out. :)
