### ISSUE TITLE
Screen Resize to fit content

### ISSUE THREAD

**Issue by matiaz** [DeveloperMaris/ToolReleases#9]
It would be nice to have the entire screen automatically resize to fit the content of the table, that way you can see all the content at the same time without having to scroll in the little screen.

**Comment by DeveloperMaris** [comment]
Thank you @matiaz for the idea. 

Will give it a try and see what happens, maybe this will be included in future updates.

**Comment by matiaz** [comment]
Excellent! love the app, great job :)

**Comment by DeveloperMaris** [comment]
Just a notice that the latest version contains increased `width` for the popover window for better readability.
